apiVersion: v1
kind: Service
metadata:
  name: blinkered
  namespace: blinkered-prod
  labels:
    app.kubernetes.io/name: blinkered
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: blinkered
  ports:
    - name: http
      port: 80
      targetPort: http
