import { byCodePoint, folder, segmentBy } from './alphabet.js'
import type { Alphabet } from './alphabet.js'

/**
 * The languages Blinkered knows how to deal a board in.
 *
 * The draw weights here are estimates, kept only until a word list exists for the language:
 * `pnpm derive` recalculates them from the language's own vocabulary, which is a far better
 * basis than anyone's intuition. See docs/PLAN.md 5.
 *
 * What is not an estimate is each alphabet's letter inventory and its diacritic policy, and
 * those are the decisions that matter. Two kinds of language:
 *
 * - accents as decoration: French, Italian, Dutch, Malay, Indonesian, and the vowels of
 *   Spanish and Portuguese. The mark folds away, so EPEE and PERE share plain E tiles, and
 *   a US keyboard can play the language. This is what every word game in these languages
 *   does, Scrabble included.
 * - diacritics as letters: Croatian Č Ć Đ Š Ž, German Ä Ö Ü, Swedish and Finnish Å Ä Ö,
 *   Norwegian Æ Ø Å, Spanish Ñ, Portuguese Ç. Own letter, own tile, own weight, no folding,
 *   because collapsing them would merge words a speaker considers different.
 */

const QU = { Q: ['U'] } as const

export const ENGLISH: Alphabet = {
  id: 'en',
  endonym: 'English',
  // Derived from the word list by tools/derive rather than copied from Scrabble: Scrabble's
  // distribution follows letters in running text, and a board has to spell dictionary words,
  // where C, L, S and P are far commoner and D, W and F rather less so.
  weights: {
    A: 9,
    B: 2,
    C: 5,
    D: 3,
    E: 10,
    F: 1,
    G: 2,
    H: 3,
    I: 9,
    J: 1,
    K: 1,
    L: 6,
    M: 3,
    N: 7,
    O: 8,
    P: 3,
    Q: 1,
    R: 7,
    S: 6,
    T: 7,
    U: 4,
    V: 1,
    W: 1,
    X: 1,
    Y: 2,
    Z: 1,
  },
  vowels: ['A', 'E', 'I', 'O', 'U'],
  rareLetters: ['J', 'K', 'Q', 'V', 'W', 'X', 'Z'],
  requires: QU,
  fold: folder(),
  segment: byCodePoint,
}

export const FRENCH: Alphabet = {
  id: 'fr',
  endonym: 'Français',
  weights: {
    A: 8,
    B: 2,
    C: 4,
    D: 4,
    E: 15,
    F: 2,
    G: 2,
    H: 2,
    I: 8,
    J: 1,
    K: 1,
    L: 6,
    M: 3,
    N: 7,
    O: 6,
    P: 3,
    Q: 1,
    R: 7,
    S: 8,
    T: 7,
    U: 6,
    V: 2,
    W: 1,
    X: 1,
    Y: 1,
    Z: 1,
  },
  vowels: ['A', 'E', 'I', 'O', 'U'],
  rareLetters: ['J', 'K', 'Q', 'W', 'X', 'Y', 'Z'],
  requires: QU,
  // CINQ and COQ exist, so the rule costs French a word or two. Worth it: a lone Q is dead
  // in almost every other case.
  fold: folder({ expand: { Œ: 'OE', Æ: 'AE' } }),
  segment: byCodePoint,
}

export const SPANISH: Alphabet = {
  id: 'es',
  endonym: 'Español',
  weights: {
    A: 12,
    B: 2,
    C: 4,
    D: 5,
    E: 13,
    F: 1,
    G: 2,
    H: 1,
    I: 7,
    J: 1,
    K: 1,
    L: 6,
    M: 3,
    N: 7,
    Ñ: 1,
    O: 9,
    P: 3,
    Q: 1,
    R: 7,
    S: 8,
    T: 5,
    U: 4,
    V: 2,
    W: 1,
    X: 1,
    Y: 1,
    Z: 1,
  },
  vowels: ['A', 'E', 'I', 'O', 'U'],
  rareLetters: ['J', 'K', 'Ñ', 'Q', 'W', 'X', 'Z'],
  requires: QU,
  // CH and LL stopped being letters of the alphabet in the 1994 reform, so they are two
  // tiles each. Ñ never was: it stays.
  fold: folder({ keep: ['Ñ'] }),
  segment: byCodePoint,
}

export const ITALIAN: Alphabet = {
  id: 'it',
  endonym: 'Italiano',
  // Twenty-one letters. J, K, W, X and Y appear only in loanwords and are not dealt.
  weights: {
    A: 11,
    B: 2,
    C: 5,
    D: 4,
    E: 11,
    F: 1,
    G: 2,
    H: 1,
    I: 11,
    L: 6,
    M: 3,
    N: 7,
    O: 10,
    P: 3,
    Q: 1,
    R: 7,
    S: 5,
    T: 6,
    U: 3,
    V: 2,
    Z: 2,
  },
  vowels: ['A', 'E', 'I', 'O', 'U'],
  rareLetters: ['H', 'Q', 'Z'],
  requires: QU,
  fold: folder(),
  segment: byCodePoint,
}

export const GERMAN: Alphabet = {
  id: 'de',
  endonym: 'Deutsch',
  weights: {
    A: 6,
    Ä: 1,
    B: 2,
    C: 3,
    D: 5,
    E: 16,
    F: 2,
    G: 3,
    H: 4,
    I: 8,
    J: 1,
    K: 2,
    L: 4,
    M: 3,
    N: 10,
    O: 3,
    Ö: 1,
    P: 1,
    Q: 1,
    R: 7,
    S: 7,
    T: 6,
    U: 4,
    Ü: 1,
    V: 1,
    W: 2,
    X: 1,
    Y: 1,
    Z: 1,
  },
  vowels: ['A', 'E', 'I', 'O', 'U', 'Ä', 'Ö', 'Ü'],
  rareLetters: ['J', 'Q', 'V', 'X', 'Y', 'Z'],
  requires: QU,
  // Eszett needs no rule: upper-casing turns it into SS on its own, which is how German
  // word games spell it. The umlauts are letters and stay.
  fold: folder({ keep: ['Ä', 'Ö', 'Ü'] }),
  segment: byCodePoint,
}

export const DUTCH: Alphabet = {
  id: 'nl',
  endonym: 'Nederlands',
  weights: {
    A: 8,
    B: 2,
    C: 2,
    D: 5,
    E: 19,
    F: 1,
    G: 3,
    H: 2,
    I: 6,
    J: 2,
    K: 2,
    L: 4,
    M: 2,
    N: 10,
    O: 6,
    P: 2,
    Q: 1,
    R: 6,
    S: 5,
    T: 7,
    U: 3,
    V: 2,
    W: 2,
    X: 1,
    Y: 1,
    Z: 1,
  },
  vowels: ['A', 'E', 'I', 'O', 'U'],
  rareLetters: ['C', 'J', 'Q', 'X', 'Y', 'Z'],
  requires: QU,
  // IJ is a single letter to a typographer and two tiles to a Dutch word game. Two tiles.
  fold: folder(),
  segment: byCodePoint,
}

export const PORTUGUESE: Alphabet = {
  id: 'pt',
  endonym: 'Português',
  weights: {
    A: 14,
    B: 2,
    C: 4,
    Ç: 2,
    D: 5,
    E: 12,
    F: 2,
    G: 2,
    H: 2,
    I: 7,
    J: 1,
    K: 1,
    L: 3,
    M: 5,
    N: 5,
    O: 10,
    P: 3,
    Q: 1,
    R: 7,
    S: 8,
    T: 5,
    U: 4,
    V: 2,
    W: 1,
    X: 1,
    Y: 1,
    Z: 1,
  },
  vowels: ['A', 'E', 'I', 'O', 'U'],
  rareLetters: ['J', 'K', 'Q', 'W', 'X', 'Y', 'Z'],
  requires: QU,
  fold: folder({ keep: ['Ç'] }),
  segment: byCodePoint,
}

/** Croatian letters, longest first so LJ beats L and DŽ beats D at the same position. */
const CROATIAN_LETTERS = [
  'DŽ',
  'LJ',
  'NJ',
  'A',
  'B',
  'C',
  'Č',
  'Ć',
  'D',
  'Đ',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'R',
  'S',
  'Š',
  'T',
  'U',
  'V',
  'Z',
  'Ž',
]

export const CROATIAN: Alphabet = {
  id: 'hr',
  endonym: 'Hrvatski',
  // Thirty letters, three of them digraphs, and no Q, W, X or Y at all. This is the
  // alphabet that proves a tile holds a string rather than a character.
  weights: {
    A: 10,
    B: 2,
    C: 2,
    Č: 2,
    Ć: 1,
    D: 4,
    DŽ: 1,
    Đ: 1,
    E: 9,
    F: 1,
    G: 2,
    H: 2,
    I: 10,
    J: 5,
    K: 4,
    L: 4,
    LJ: 1,
    M: 4,
    N: 6,
    NJ: 1,
    O: 9,
    P: 3,
    R: 6,
    S: 5,
    Š: 2,
    T: 5,
    U: 4,
    V: 3,
    Z: 2,
    Ž: 1,
  },
  vowels: ['A', 'E', 'I', 'O', 'U'],
  rareLetters: ['DŽ', 'Đ', 'F', 'Ć', 'Ž', 'LJ', 'NJ'],
  requires: {},
  fold: folder({ keep: ['Č', 'Ć', 'Đ', 'Š', 'Ž'] }),
  segment: segmentBy(CROATIAN_LETTERS),
}

/**
 * Malay and Indonesian share one alphabet and differ in vocabulary: Indonesian borrowed from
 * Dutch, Malaysian from English, and the spelling was unified in 1972. Two word lists, one
 * letter inventory, and no diacritics anywhere, which makes them the least friction of the
 * set.
 */
const MALAY_WEIGHTS = {
  A: 19,
  B: 4,
  C: 2,
  D: 4,
  E: 8,
  F: 1,
  G: 4,
  H: 3,
  I: 8,
  J: 2,
  K: 6,
  L: 4,
  M: 5,
  N: 9,
  O: 3,
  P: 4,
  Q: 1,
  R: 6,
  S: 5,
  T: 6,
  U: 6,
  V: 1,
  W: 1,
  X: 1,
  Y: 2,
  Z: 1,
}

export const MALAY: Alphabet = {
  id: 'ms',
  endonym: 'Bahasa Melayu',
  weights: MALAY_WEIGHTS,
  vowels: ['A', 'E', 'I', 'O', 'U'],
  rareLetters: ['Q', 'V', 'X', 'Z'],
  requires: QU,
  fold: folder(),
  segment: byCodePoint,
}

export const INDONESIAN: Alphabet = {
  ...MALAY,
  id: 'id',
  endonym: 'Bahasa Indonesia',
}

export const RUSSIAN: Alphabet = {
  id: 'ru',
  endonym: 'Русский',
  // Thirty-two tiles: Ё is folded onto Е, as Russian word games do.
  weights: {
    А: 8,
    Б: 2,
    В: 4,
    Г: 2,
    Д: 3,
    Е: 9,
    Ж: 1,
    З: 2,
    И: 7,
    Й: 1,
    К: 3,
    Л: 4,
    М: 3,
    Н: 7,
    О: 11,
    П: 3,
    Р: 5,
    С: 5,
    Т: 6,
    У: 3,
    Ф: 1,
    Х: 1,
    Ц: 1,
    Ч: 1,
    Ш: 1,
    Щ: 1,
    Ъ: 1,
    Ы: 2,
    Ь: 2,
    Э: 1,
    Ю: 1,
    Я: 2,
  },
  vowels: ['А', 'Е', 'И', 'О', 'У', 'Ы', 'Э', 'Ю', 'Я'],
  rareLetters: ['Ъ', 'Щ', 'Э', 'Ц', 'Ф', 'Ж', 'Х'],
  requires: {},
  fold: folder({ expand: { Ё: 'Е' } }),
  segment: byCodePoint,
}

export const SWEDISH: Alphabet = {
  id: 'sv',
  endonym: 'Svenska',
  weights: {
    A: 9,
    Å: 2,
    Ä: 2,
    B: 2,
    C: 1,
    D: 5,
    E: 9,
    F: 2,
    G: 3,
    H: 2,
    I: 5,
    J: 1,
    K: 3,
    L: 5,
    M: 3,
    N: 7,
    O: 5,
    Ö: 2,
    P: 2,
    Q: 1,
    R: 7,
    S: 6,
    T: 7,
    U: 3,
    V: 2,
    W: 1,
    X: 1,
    Y: 1,
    Z: 1,
  },
  vowels: ['A', 'E', 'I', 'O', 'U', 'Y', 'Å', 'Ä', 'Ö'],
  rareLetters: ['C', 'Q', 'W', 'X', 'Z'],
  requires: QU,
  fold: folder({ keep: ['Å', 'Ä', 'Ö'] }),
  segment: byCodePoint,
}

export const NORWEGIAN: Alphabet = {
  id: 'no',
  endonym: 'Norsk',
  weights: {
    A: 6,
    Å: 2,
    Æ: 1,
    B: 2,
    C: 1,
    D: 5,
    E: 15,
    F: 2,
    G: 4,
    H: 2,
    I: 5,
    J: 2,
    K: 4,
    L: 5,
    M: 3,
    N: 7,
    O: 4,
    Ø: 2,
    P: 2,
    Q: 1,
    R: 8,
    S: 6,
    T: 7,
    U: 3,
    V: 2,
    W: 1,
    X: 1,
    Y: 1,
    Z: 1,
  },
  vowels: ['A', 'E', 'I', 'O', 'U', 'Y', 'Æ', 'Ø', 'Å'],
  rareLetters: ['C', 'Q', 'W', 'X', 'Z'],
  requires: QU,
  fold: folder({ keep: ['Æ', 'Ø', 'Å'] }),
  segment: byCodePoint,
}

export const FINNISH: Alphabet = {
  id: 'fi',
  endonym: 'Suomi',
  // B, C, F, Q, W, X, Z and Å are all effectively foreign to Finnish, hence weight one and
  // no doubling. Ä and Ö are ordinary letters and common.
  weights: {
    A: 12,
    Å: 1,
    Ä: 5,
    B: 1,
    C: 1,
    D: 1,
    E: 8,
    F: 1,
    G: 1,
    H: 2,
    I: 10,
    J: 2,
    K: 5,
    L: 5,
    M: 3,
    N: 9,
    O: 5,
    Ö: 1,
    P: 2,
    Q: 1,
    R: 2,
    S: 7,
    T: 9,
    U: 5,
    V: 2,
    W: 1,
    X: 1,
    Y: 2,
    Z: 1,
  },
  vowels: ['A', 'E', 'I', 'O', 'U', 'Y', 'Ä', 'Ö', 'Å'],
  rareLetters: ['B', 'C', 'F', 'Q', 'W', 'X', 'Z', 'Å'],
  // Finnish has no native Q, so there is no lone-Q problem to rule out.
  requires: {},
  fold: folder({ keep: ['Å', 'Ä', 'Ö'] }),
  segment: byCodePoint,
}

const ALPHABETS: Readonly<Record<string, Alphabet>> = Object.fromEntries(
  [
    ENGLISH,
    FRENCH,
    SPANISH,
    ITALIAN,
    GERMAN,
    DUTCH,
    PORTUGUESE,
    CROATIAN,
    MALAY,
    INDONESIAN,
    RUSSIAN,
    SWEDISH,
    NORWEGIAN,
    FINNISH,
  ].map((alphabet) => [alphabet.id, alphabet]),
)

export const DEFAULT_LANGUAGE = ENGLISH.id

/**
 * Every language an alphabet exists for. Not the same as every language that can be played:
 * that also needs a word list, and the web app offers only the languages whose list is
 * actually present.
 */
export const ALPHABET_IDS: readonly string[] = Object.keys(ALPHABETS)

export function alphabetFor(id: string): Alphabet {
  const alphabet = ALPHABETS[id]
  if (!alphabet) throw new RangeError(`no alphabet for language ${id}`)
  return alphabet
}
